### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by rifkydoang**

### CODE REVIEW

**Comment by ByLaaaa** [comment]
bgst

**Comment by rifkydoang** [comment]
> 

woiii

**Comment by ByLaaaa** [comment]
> > 
> 
> woiii

napa cok

**Comment by rifkydoang** [comment]
> > > 
> > 
> > 
> > woiii
> 
> napa cok

share lock share lock

**Comment by ByLaaaa** [comment]
> > > > 
> > > 
> > > 
> > > woiii
> > 
> > 
> > napa cok
> 
> share lock share lock

letris sini cokk

**Comment by rifkydoang** [comment]
> > > > > 
> > > > 
> > > > 
> > > > woiii
> > > 
> > > 
> > > napa cok
> > 
> > 
> > share lock share lock
> 
> letris sini cokk

otw

**Pull request merged**
